/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2026-03-16 05:32:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class domXSS_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1773634462582L));
    _jspx_dependants.put("jar:file:/D:/CampStudy/front/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DOMXSS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <style>\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("		/* 브라우저 해시는 서버는 처리 불가능하므로 스크립트 통해 브라우저에서 url해결 후 서버로 요청을 진행\r\n");
      out.write("		 react는 url이 #통해 연결돼도 서버 요청과 연결되지 않으면 자유롭긴함, 연결되면 문제있음...\r\n");
      out.write("		 브라우저 요청에 hash가 포함되어 있는지 확인\r\n");
      out.write("		 현재브라우저의 url을 hash 기준 분리\r\n");
      out.write("		 https://www.naver.com/#example-> #기준으로 분리, 첫번째 문자열을 반환(example반환)\r\n");
      out.write("		\r\n");
      out.write("		*/\r\n");
      out.write("		const hash = window.location.hash.slice(1);\r\n");
      out.write("		\r\n");
      out.write("		if(hash)\r\n");
      out.write("			// decodeURIComponent(\"first.jsp\")는 파라미터로 전달된 내용을 uri로 구성\r\n");
      out.write("			// 브라우저의 현재 요청 uri 뒤에 first.jsp 추가하여 요청 가능한 uri로 만들어 줌\r\n");
      out.write("			// 실행은 되지만 프로그램에 영향을 미치지 않음\r\n");
      out.write("			window.location.href = decodeURIComponent(window.location.hash.slice(1));\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		/* 구조 제외 식별자 사용(구조는 메소드에 의해 만들어지는 코드)\r\n");
      out.write("		1. http://localhost:8080/DOMXSS/domXSS.jsp#first.jsp 요청되면\r\n");
      out.write("		2. hashchange 이벤트 발생\r\n");
      out.write("		3. 해시 기준으로 slice 진행 -> first.jsp 반환\r\n");
      out.write("		4. 현재 요청서버에 맞는 url을 구성 후 반환\r\n");
      out.write("		http://localhost:8080/DOMXSS/domXSS.jsp -> 페이지명을 first.jsp로 수정 후 반환\r\n");
      out.write("			http://localhost:8080/DOMXSS/first.jsp 요청 url이 생성됨\r\n");
      out.write("		window.location.href-> http://localhost:8080/DOMXSS/domXSS.jsp/first.jsp로 지정됨 => 요청진행\r\n");
      out.write("		*/\r\n");
      out.write("		window.addEventListener('hashchange', function(){\r\n");
      out.write("			window.location.href = decodeURIComponent(window.location.hash.slice(1));\r\n");
      out.write("		});// 영향을 줌\r\n");
      out.write("    </script>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>DOM Based XSS 공격</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<h1>DOM Based XSS 공격</h1>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <a id=\"first\" href=\"#first.jsp\" class=\"item\">First 바로가기</a>\r\n");
      out.write("    <a id=\"second\" href=\"#second.jsp\" class=\"item\">Second 바로가기</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
