/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2026-03-13 06:07:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <style>\r\n");
      out.write("            .form {\r\n");
      out.write("                border: #323232 solid 1px;\r\n");
      out.write("                margin: auto;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                width: 70vw;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form__input {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form__input>div {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .form__button {\r\n");
      out.write("                margin-top: 10px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .container {\r\n");
      out.write("                position: relative;\r\n");
      out.write("                overflow-x: auto;\r\n");
      out.write("                border: #323232 solid 1px;\r\n");
      out.write("                margin: 10px auto;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                width: 70vw;\r\n");
      out.write("                height: 300px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .container__header {\r\n");
      out.write("                position: absolute;\r\n");
      out.write("                top: 1rem;\r\n");
      out.write("                right: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("        <script type='text/javascript'>\r\n");
      out.write("        	// js의 정규 표현식 객체는 RegExp를 활용 인스턴스 생성 또는 리터럴 표기법을 활용해서 인스턴스 생성\r\n");
      out.write("        	// 리터럴 표기법은 정규식 패턴 문자를 / 정규식패턴문자 / 로 묶어서 인스턴스 생성하는 기능\r\n");
      out.write("        	let re1 = new RegExp('ab+c'); // 정규식에서 +는 반복을 의미, +앞의 문자를 1회 이상 반복하는 패턴\r\n");
      out.write("        	let re2 = new RegExp(/abc/); // 문자열에 abc 패턴 있는지 확인\r\n");
      out.write("        	let re3 = /abc/;\r\n");
      out.write("        	\r\n");
      out.write("        	// RegExp.test(\"문자열\") : 파라미터로 전달된 문자열이 정규표현식의 패턴과 일치하는지의 결과 ture/false로 반환하는 메소드\r\n");
      out.write("        	console.log(re1.test(\"abcde\") );\r\n");
      out.write("        	console.log(re2.test(\"abbccde\"));\r\n");
      out.write("        	console.log(re3.test(\"abcde\"));\r\n");
      out.write("        	// 참조변수없이 정규식 패턴 그대로 사용\r\n");
      out.write("        	console.log(/abc/.test(\"abbcde\"));\r\n");
      out.write("        	\r\n");
      out.write("        	/*  정규식 기호: ^(시작값을 의미, 먼저 표시), +(1회 이상 반복), $(종료값을 의미, 뒤에표시)\r\n");
      out.write("        		정규식 기호: [] (패턴의 집합), |(or의 의미), - (순서적인 범위를 표현)\r\n");
      out.write("        		[]안의 문자중 하나로 시작해야되고 문자는 1번이상 반복될 수 있고 []안의 문자중 하나로 끝나야 함\r\n");
      out.write("        	*/\r\n");
      out.write("        	const regex = /^[ㄱ-ㅎ|가-힣|a-z|A-Z|0-9| |]+$ /;\r\n");
      out.write("        	console.log(regex.test(\"<script\"));	// <로 시작\r\n");
      out.write("        	console.log(regex.test(\"script>\"));	// >로 끝\r\n");
      out.write("        	console.log(regex.test(\"scr<ipt\"));	// []안에 없는 문자가 포함\r\n");
      out.write("        	console.log(regex.test(\"script\"));	// []안에있는 문자로 시작되고 종료되는 반복\r\n");
      out.write("        	\r\n");
      out.write("        	function submitHandler(){\r\n");
      out.write("        		const keyword = document.querySelector(\"input[name='keyword']\");\r\n");
      out.write("        		const reg = /^[ㄱ-ㅎ|가-힣|a-z|A-Z|0-9| |]+$/;\r\n");
      out.write("        		if(!reg.test(keyword.value)) {\r\n");
      out.write("        			alert(\"특수문자는 입력할 수 없습니다.\"); \r\n");
      out.write("        			return false;\r\n");
      out.write("        		}\r\n");
      out.write("        		return true;\r\n");
      out.write("        	}\r\n");
      out.write("        </script>\r\n");
      out.write("        <title>Insert title here</title>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("    ");
  
      out.write("\r\n");
      out.write("        <h1>Reflected XSS 공격 </h1>\r\n");
      out.write("        <div class=\"form\">\r\n");
      out.write("            <form action=\"reflected2.jsp\" method=\"get\"onsubmit=\"return submitHandler()\">\r\n");
      out.write("                <div class=\"form__input\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <span> 검색 </span>\r\n");
      out.write("                        <!-- 입력되는 입력값은 reflected.jsp 서버 페이지쪽으로 keyword 파라미터에 담겨서 전달됨 -->\r\n");
      out.write("                        <input type=\"text\" name=\"keyword\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input class=\"form__button\" type=\"submit\" value=\" 전송 \" />\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- main.jsp를 요청할 때 keyword 파라미터가 전달되면 전달되는 파라미터 값을 화면에 표현 -->\r\n");
      out.write("            ");
 
            	request.setCharacterEncoding("UTF-8");
            	String key = request.getParameter("keyword");
            	if(key == null) { key = ""; }
            
      out.write("\r\n");
      out.write("             <div class=\"container__header\"> 검색어 ");
      out.print( key  );
      out.write("\r\n");
      out.write("             </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
